### ISSUE TITLE
Checking grabbed values does not work

### ISSUE THREAD

**Issue by wiggly** [hidroh/cucumber-api#11]
Grabbed values are now being places in instance variables and are being looked up by the resolve(url) method.

The following code fails;

```
Feature: Property creation
  
  Scenario: Create a simple property
    Given I send and accept JSON
    When I set JSON request body to:
      """
      {
      "area_name": "Holborn",
      "address": "321 High Holborn",
      "post_code": "WC2B 5FG",
      "available": true
      }
      """
    And I send a POST request to "http://localhost:3000/properties" 
    Then the response status should be "201"
    And the JSON response should have key "id"
    And I grab "id" as "uuid"
    And the JSON response should have "id" of type string and value "{uuid}"
```

with the error;

```
    And the JSON response should have "id" of type string and value "{uuid}" # cucumber-api-0.4/lib/cucumber-api/steps.rb:183
      Did you forget to "grab" uuid? (RuntimeError)
      features/property_create.feature:17:in `And the JSON response should have "id" of type string and value "{uuid}"'
```

Adding some tracing statements shows that the instance (self) being used when grabbing values and that used when resolving them is different, hence no instance variables are shared.

**Comment by wiggly** [comment]
After reading the cucumber docs it seems the `resolve` function should be included in the World rather than free-floating in the steps definition file.

**Comment by wiggly** [comment]
So, the strange thing is that this only doesn't work when I run it in my rails project.

When I run the sample feature it works.

The PR I created does put the helper in a module as suggested by the cucumber team though and then it works either way. That PR requires the addressable fix be added first otherwise Travis won't even attempt to run the tests.

**Comment by hidroh** [comment]
Do you have the Cucumber docs that mentions it should be in World? Sorry have been away from this project for too long.

**Comment by wiggly** [comment]
Yep, here;

https://github.com/cucumber/cucumber/wiki/A-Whole-New-World

http://drnicwilliams.com/2009/04/15/cucumber-building-a-better-world-object/

**Comment by hidroh** [comment]
This is good enough for me:

> Note that every scenario is run in a separate instance of the world, so there is no implicit state-sharing from scenario to scenario.
