### ISSUE TITLE
Add a custom step to clear cache on demand from feature file

### ISSUE THREAD

**Issue by sandeepnagra** [hidroh/cucumber-api#19]
Here's what I use in my project:

Given(/^I clear the response cache$/) do
  $cache = {}
end

**Comment by sandeepnagra** [comment]
I can create a pull request if you think you can add it to steps.rb file

**Comment by hidroh** [comment]
You're welcome to make PR!

**Comment by biggianteye** [comment]
Hi there. What's the likelihood that the above PR will get merged? Being able to either disable the response cache or clear it would be very useful to me.

**Comment by hidroh** [comment]
@kevgatch I need the build to be green for me to merge that PR.
