### ISSUE TITLE
'Given I clear the response cache' is undefined

### ISSUE THREAD

**Issue by xliiauo** [hidroh/cucumber-api#30]
Hi, I was trying to disable response cacheing with 'Given I clear the response cache'. But, it says it's undefined. Please could you have a look for me. Thank you very much.
￼
<img width="550" alt="screenshot" src="https://user-images.githubusercontent.com/9721723/44529620-7629b800-a6e4-11e8-8254-f79cc1a5275a.png">

**Comment by xliiauo** [comment]
Gems included by the bundle:
  * addressable (2.5.0)
  * aws-sigv4 (1.0.3)
  * backports (3.11.3)
  * builder (3.2.3)
  * bundler (1.16.3)
  * coderay (1.1.2)
  * cucumber (3.1.2)
  * cucumber-api (0.6)
  * cucumber-core (3.2.0)
  * cucumber-expressions (6.0.1)
  * cucumber-tag_expressions (1.1.1)
  * cucumber-wire (0.0.1)
  * diff-lcs (1.3)
  * domain_name (0.5.20180417)
  * gherkin (5.1.0)
  * http-cookie (1.0.3)
  * json-schema (2.8.0)
  * jsonpath (0.9.3)
  * method_source (0.9.0)
  * mime-types (3.2.2)
  * mime-types-data (3.2018.0812)
  * multi_json (1.13.1)
  * multi_test (0.1.2)
  * netrc (0.11.0)
  * pry (0.11.3)
  * public_suffix (2.0.5)
  * rest-client (2.0.2)
  * to_regexp (0.2.1)
  * unf (0.1.4)
  * unf_ext (0.0.7.5)

**Comment by biggianteye** [comment]
Clearing the response cache is only available in master at the moment. It is not in a released version.

**Comment by hidroh** [comment]
@biggianteye I think I forget to publish a new version with that change, I'll do that later today!

**Comment by hidroh** [comment]
Fixed in 0.7
