### ISSUE TITLE
Gem Load Error

### ISSUE THREAD

**Issue by mattlindsey** [hidroh/cucumber-api#6]
Cucumber-Api is working fine from 'cucumber' command, but running 'rspec' or 'rails s' gives the following error:

/Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'cucumber-api'. (Bundler::GemRequireError)
Gem Load Error is: undefined method `Given' for main:Object
Backtrace for gem load error is:
/Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/cucumber-api-0.4/lib/cucumber-api/steps.rb:11:in `<top (required)>'
/Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/cucumber-api-0.4/lib/cucumber-api.rb:1:in `<top (required)>'
/Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `require'
/Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `each'
/Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `block in require'
/Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `each'
/Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `require'
/Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler.rb:106:in `require'
/Users/mattlindsey/Documents/github/redeemify/config/application.rb:7:in `<top (required)>'
/Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:78:in `require'
/Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:78:in `block in server'
/Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
/Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `server'
/Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
/Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

**Comment by adimircolen** [comment]
In my case I tried
`gem 'cucumber-api', require: false`
on Gemfile and it's worked

**Comment by mattlindsey** [comment]
Appears we're using this now
```
gem 'cucumber-api-steps', :require => false
```
So I'll close this issue.
